name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - uses: finnp/create-file-action@master
        env:
          FILE_NAME: "local.properties"

      - name: Generate Keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'android-signing-keystore.jks'
          encodedString: ${{ secrets.SIGNING_KEYSTORE_FILE }}

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Debug APK
        run: ./gradlew assembleDevDebug
        env:
          SIGNING_KEYSTORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_KEYSTORE_FILE: "../android-signing-keystore.jks"